- adobe
- affirm
- airbnb
- algolia
- alphabet
- alto
- amd
- amplitude
- anaplan
- anthem_ai
- apple
- asana
- atlassian
- audible
- automation_anywhere
- autodesk
- block
- brex
- cadence
- calico
- canva
- capella_space
- carto
- chaos
- chewy
- chronosphere
- cisco
- coinbase
- cohesity
- confluence
- conjur
- cloudflare
- copilot_ai
- coursera
- Cruise
- Databricks
- Datadog
- Datastax
- Docker
- DoorDash
- Dropbox
- Duolingo
- Elastic
- Figma
- FindMind
- Finix
- Flexport
- Github
- Gitlab
- Gong
- GoodRx
- Grammarly
- HashiCorp
- Heap
- Hopin
- Hortonworks
- Humane
- Hubspot
- Instacart
- Intuit
- Juniper
- Khan_Academy
- Khoros
- Klaviyo
- Lacework
- LastPass
- Lyft
- Meta
- Microsoft
- Mixpanel
- MongoDB
- Mux
- Nvidia
- Notion
- Okta
- OpenAI
- OpenDoor
- PagerDuty
- Palantir
- PayPal
- Pinterest
- Plaid
- Postman
- Qualtrics
- Reddit
- Rippling
- Roblox
- Roku
- Salesforce
- Samsara
- ScaleAI
- Segment
- ServiceNow
- Shopify
- Slack
- Snowflake
- Splunk
- Spotify
- Stripe
- SumoLogic
- Superhuman
- SurveyMonkey
- Synopsys
- Tableau
- Tesla
- ThoughtSpot
- Twilio
- Uber
- Unity
- Upstart
- Vercel
- Verkada
- VMware
- Weave
- Webflow
- Workday
- Yelp
- Zendesk
- Zoom
- Zuora