# Only *human* inputs the program still needs
locations:
  - "remote"
  - "san francisco"
  - "san jose"
  - "palo alto"
  - "mountain view"

titles:
  - "Product Manager"
  - "Senior Product Manager"
  - "Principal Product Manager"
  - "Director of Product"
  - "Head of Product"