name: job-hunter-daily
on:
  schedule:
    - cron: "0 14 * * *"   # 14:00 UTC ≈ 7 AM PT
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install poetry
      - run: poetry install --no-root
      - run: poetry run scrape-stripe
      - run: poetry run embed-jobs
      - run: poetry run match-stripe my-resume > matches.txt
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          to: you@gmail.com
          subject: "Your top job matches – ${{ github.run_id }}"
          body: |
            $(cat matches.txt)

