name: job-hunter-daily

on:
  schedule:
    - cron: "0 14 * * *"    # 07:00 PT every day
  workflow_dispatch:        # enables the “Run workflow” button

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install project deps
        run: poetry install --no-root

      - name: Scrape all jobs
        run: poetry run scrape-all

      - name: Embed job descriptions
        run: poetry run python -m job_hunter.matching.embed_jobs

      - name: Match résumé vs jobs
        run: |
          poetry run match-stripe my-resume > matches.txt
          echo '### Top Matches' >> $GITHUB_STEP_SUMMARY
          cat matches.txt        >> $GITHUB_STEP_SUMMARY

      #- name: Send email
      #  uses: dawidd6/action-send-mail@v3
      #  with:  
      #    server_address: smtp.gmail.com
      #    server_port: 465
      #    username: ${{ secrets.EMAIL_USER }}
      #    password: ${{ secrets.EMAIL_PASS }}
      #    to: you@gmail.com
      #    subject: "Your top job matches – ${{ github.run_id }}"
      #    body: |
      #      $(cat matches.txt)

